### ISSUE TITLE
Module netbox_device_interface doesn't seems to work properly

### ISSUE THREAD

**Issue by achrstl** [FragmentedPacket/netbox_modules#23]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

I'm currently using your collection with "netbox_device", "netbox_ip_address" and "netbox_device_interface". But with the last one it seem's that ansible doesn't find any action related.

Ansible version: 2.8.5
Netbox version: 2.6.5

I have this message : 

"ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The offending line appears to be:

- name: Create interface within Netbox with only required information
  ^ here"

##### STEPS TO REPRODUCE

I'm using examples in your modules documentation, so netbox_device and netbox_ip_address are working but not netbox_device_interface

```yaml

- name: Create device within Netbox with only required information
  collections:
     - fragmentedpacket.netbox_modules
  netbox_device:
    netbox_url: "{{ net_url }}"
    netbox_token: "{{ net_token }}"
    data:
      name: "{{ inventory_hostname }}"
      device_type: "{{ type }}"
      platform: "{{ platform }}"
      device_role: "{{ role }}"
      site: "{{ site }}"
      rack: "{{ rack }}"
      position: "{{ position }}"
      face: "{{ face }}"
    state: "{{ state }}"

- name: Create device interface with only required information
  collections:
     - fragmentedpacket.netbox_modules
  netbox_device_interface:
    netbox_url: "{{ net_url }}"
    netbox_token: "{{ net_token }}"
    data:
      device: "{{ inventory_hostname }}"
      name: Vme.0
    state: "{{ state }}"

- name: Create management IP linked to the device
  collections:
     - fragmentedpacket.netbox_modules
  netbox_ip_address:
    netbox_url: "{{ net_url }}"
    netbox_token: "{{ net_token }}"
    data:
      address: "{{ ansible_host }}"
      description: "Mgmt : {{ inventory_hostname }}"
      interface:
        name: Vme.0
        device: "{{ inventory_hostname }}"
    state: "{{ state }}"
```

##### EXPECTED RESULTS

Create a device with one interface Vme.0 and one IP attached to it.

##### ACTUAL RESULTS

If i'm running the two task without netbox_device_interface, the device is created and i can create one IP.

So for the moment i'm using the official "netbox_interface" and it's working like expected.
But if i could use all your modules it would be great :)

**Comment by achrstl** [comment]
Thanks for your reply ! Indeed it's working when i'm calling the module with   ```fragmentedpacket.netbox_modules.netbox_device_interface```

But why the others are working with ? 

```
  collections:
     - fragmentedpacket.netbox_modules
```


And i try to set the collection in my playbook but it seems that it wasn't taking in consideration by ansible.

```
---
- name: Add devices in netbox
  hosts: all
  gather_facts: False
  connection: local
  collections:
    - fragmentedpacket.netbox_modules

  vars:
    net_url: http://xyz
    state: present

  roles:
    - netbox_network_device
```

With this error : 
```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
```

**Comment by achrstl** [comment]
My playbook : insert_device_into_netbox.yml

```
---
- name: Add devices in netbox
  hosts: test-device.yml
  gather_facts: False
  connection: local
 
  vars:
    net_url: http://xyz
    state: present

  roles:
    - netbox_network_device
```

For the moment there is only one task in my role "netbox_network_device"

```
├── ansible.cfg
├── inventories
│   ├── development
│   │   ├── group_vars
│   │   └── host_vars
│   └── production
│       ├── group_vars
│       │   ├── all.yml
│       ├── host_vars
│       │   ├── test-device.yml
│       └── hosts
├── playbooks
│   ├── network
│   │   ├── juniper
│   └── system
│       └── insert_device_into_netbox.yml
├── roles
│   ├── netbox_network_device
│   │   ├── defaults
│   │   │   └── main.yml  --> empty
│   │   ├── tasks
│   │   │   └── main.yml
│   │   ├── templates
│   │   └── vars
│   │       └── main.yml --> empty

```

```
- name: Create device within Netbox with only required information
  collections:
     - fragmentedpacket.netbox_modules
  netbox_device:
    netbox_url: "{{ net_url }}"
    netbox_token: "{{ net_token }}"
    data:
      name: "{{ inventory_hostname }}"
      device_type: "{{ type }}"
      platform: "{{ platform }}"
      device_role: "{{ role }}"
      site: "{{ site }}"
      rack: "{{ rack }}"
      position: "{{ position }}"
      face: "{{ face }}"
    state: "{{ state }}"

- name: Create device interface with only required information
  collections:
     - fragmentedpacket.netbox_modules
  netbox_device_interface:
    netbox_url: "{{ net_url }}"
    netbox_token: "{{ net_token }}"
    data:
      device: "{{ inventory_hostname }}"
      name: Vme.0
    state: "{{ state }}"

- name: Create management IP linked to the device
  collections:
     - fragmentedpacket.netbox_modules
  netbox_ip_address:
    netbox_url: "{{ net_url }}"
    netbox_token: "{{ net_token }}"
    data:
      address: "{{ ansible_host }}"
      description: "Mgmt : {{ inventory_hostname }}"
      interface:
        name: Vme.0
        device: "{{ inventory_hostname }}"
    state: "{{ state }}"
```
