### ISSUE TITLE
netbox_device_role is not reporting an error when color is missing

### ISSUE THREAD

**Issue by dgarros** [FragmentedPacket/netbox_modules#24]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The module not returning an error when color is missing

##### STEPS TO REPRODUCE
I tried to create new device_role using the `netbox_device_role` module but I forgot to specify `color`
```yaml
- name: Create Device Role in Netbox
      netbox_device_role:
        netbox_url: "{{ netbox_address }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{role}}"
          color: 
        state: present
      delegate_to: localhost
      tags: [device_role]
```

##### EXPECTED RESULTS
I would expect the execution to fail since `color` is mandatory 

##### ACTUAL RESULTS
The module is not reporting an error and unless running in debug more there is no indication that something is wrong
```
ok: [mydevice -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "name": "myrole",
                "slug": "myrole"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://host.docker.internal:8001",
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "{\"color\":[\"This field is required.\"]}"
}

```
