### ISSUE TITLE
Updating of vm_interfaces fails

### ISSUE THREAD

**Issue by pugnacity** [FragmentedPacket/netbox_modules#40]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
Creating interfaces for VMs generates an error when the interface name is already taken by an other VM

##### STEPS TO REPRODUCE
Create to VMs within Netbox and assign the interface ens192 to the VMs
Try to update the MAC Adress for the VMs with the following task:
```
- name: Create interface
  fragmentedpacket.netbox_modules.netbox_vm_interface:
    netbox_url:  "{{ netbox_url }}"
    netbox_token:  "{{ netbox_token }}"
    data:
      virtual_machine: "{{ inventory_hostname }}"
      name: "{{ ansible_default_ipv4.interface }}"
      mac_address: "{{ ansible_default_ipv4.macaddress }}"
      mtu: 1500
      enabled: true
  delegate_to: localhost
  become: false
```

##### EXPECTED RESULTS
Update the already existing interface

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_fragmentedpacket.netbox_modules.netbox_vm_interface_payload_ycs6qc_9/ansible_fragmentedpacket.netbox_modules.netbox_vm_interface_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/module_utils/netbox_virtualization.py", line 71, in run
    self.nb_object = nb_endpoint.get(**object_query_params)
  File "/home/user/python3/ansible_2.9/lib/python3.7/site-packages/pynetbox/core/endpoint.py", line 141, in get
    "get() returned more than one result. "

fatal: [pll0400-ipam001.domain.loc -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "enabled": true,
                "mtu": 1500,
                "name": "foo",
                "virtual_machine": 160
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://pll0400-ipam001.domain.loc",
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "More than one result returned for foo"
}


```
