### ISSUE TITLE
add support for custom_fields for netbox_virtual_machine

### ISSUE THREAD

**Issue by pugnacity** [FragmentedPacket/netbox_modules#42]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It would be great to support custom_fields for netbox_virtual_machine

##### STEPS TO REPRODUCE

```yaml
    - name: Create VMs 
      fragmentedpacket.netbox_modules.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          cluster: "{{ item.cluster  }}"
          virtual_machine_role: "{{ item.virtual_machine_role|default(omit) }}"
          vcpus: "{{ item.vcpus|default(omit) }}"
          tenant: "{{ item.tenant|default(omit) }}"
          platform: "{{ item.platform|default(omit) }}"
          memory: "{{ item.memory|default(omit) }}"
          disk: "{{ item.disk|default(omit) }}"
          status: "{{ item.status|default(Active) }}"
          tags: "{{ item.tags|default(omit) }}"
          custom_fields: "{{ item.custom_fields|default(omit) }}"
        state: "{{ item.state|default(omit) }}"
      run_once: true
      delegate_to: localhost
      become: false
      loop: "{{ netbox_virtual_machines }}"
      when: netbox_virtual_machines is defined
```

##### ACTUAL RESULTS
custom_fields are ignored

**Comment by FragmentedPacket** [comment]
@pugnacity I tested this simply with just a single custom field and passing in boolean:
```
- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - fragmentedpacket.netbox_modules

  tasks:
    - name: Create device within Netbox with only required information
      netbox_virtual_machine:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          name: test100-vm
          cluster: Test Cluster
          custom_fields:
            works: False
        state: present
```
And I see the following result:
```
TASK [Create device within Netbox with only required information] ***************************************************************************************************************************task path: /src/netbox-vm.yml:9
changed: [localhost] => changed=true
  msg: virtual_machine test100-vm updated
  virtual_machine:
    cluster: 1
    comments: ''
    config_context: {}
    created: '2019-11-26'
    custom_fields:
      works: false
    disk: null
    id: 1
    last_updated: '2019-11-27T23:16:03.710219Z'
    local_context_data: null
    memory: null
    name: test100-vm
    platform: null
    primary_ip: null
    primary_ip4: null
    primary_ip6: null
    role: null
    site: 1
    status: 1
    tags: []
    tenant: null
    vcpus: null
```
And if I check the UI, it gets changed.

Could you show me your `custom_fields` data? Is it a dictionary?
