### ISSUE TITLE
Still seeing the msg: 'Multiple results found while searching for key: rack'

### ISSUE THREAD

**Issue by richardjohnallsopp** [FragmentedPacket/netbox_modules#43]
##### ISSUE TYPE

 - Module question
 - Documentation update
##### SUMMARY

Not sure how to verify that the collections are working or being used? I really want to use your modules to manage our Netbox instance, but after installing the prerequisites, and the collections via ansible-galaxy and tagging them in the playbook I still see the rack key error.

I know that the rack name is unique within our Netbox deployment. 
##### STEPS TO REPRODUCE

```yaml
# PLAYBOOK
---
- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - fragmentedpacket.netbox_modules

  vars_files:
    - /home/flynn/ansible/playbooks/netbox/vault/netbox
    #- /home/flynn/ansible/playbooks/netbox/group_vars/nasuni.yml
    - /home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml

  roles:
    - netbox_add_device
    - netbox_assign_ip

# ROLE
---
# tasks file for netbox_add_device
    - name: "Create device within Netbox with only required information"
      netbox_device:
        netbox_url: 
        netbox_token: "{{  netbox_key  }}"
        data:
          name: "{{ item.value.dname }}"
          device_type: "{{ item.value.dtype }}"
          device_role: "{{ item.value.drole }}"
          site: "{{ item.value.dsite }}"
          rack: "{{ item.value.drack }}"
          position: "{{ item.value.dposition }}"
          face: "{{ item.value.dface }}"
          state: "{{ item.value.dstate }}"
        state: present
      loop: "{{ query('dict', devices) }}"
      tags: add_device

```

##### ACTUAL RESULTS

```
*
failed: [localhost] (item={'key': u'device1', 'value': {u'dname': u'test.machine.net', u'dtype': u'Edge Appliance N4040', u'dstate': u'Planned', u'drack': u'TEST-NEW-RACK-01', u'dsite': u'TEST', u'drole': u'NAS', u'dface': u'Front', u'dposition': u'16'}}) => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  ansible_loop_var: item
  item:
    key: device1
    value:
      dface: Front
      dname: test.machine.net
      dposition: '16'
      drack: TEST-NEW-RACK-01
      drole: NAS
      dsite: TEST
      dstate: Planned
      dtype: Edge Appliance N4040
  msg: 'Multiple results found while searching for key: rack'


```

**Comment by richardjohnallsopp** [comment]
Hey I hope this is the right place to ask this and it's very possible that I've done something wrong as collections are new to me, but I've followed all the instructions to get this far.

**Comment by FragmentedPacket** [comment]
If you run the playbook with `-vvvv` there should be a line that states `Using module ...` that should show you what it is attempting to use.

Let me know what that output is and we can go from there.

**Comment by richardjohnallsopp** [comment]
flynn@ncl-ansible-01:~/ansible/playbooks/netbox$ ansible-playbook netbox_test.yaml -vvvv
ansible-playbook 2.9.1
  config file = /home/flynn/ansible/playbooks/netbox/ansible.cfg
  configured module search path = [u'/home/flynn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
Using /home/flynn/ansible/playbooks/netbox/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/flynn/ansible/playbooks/netbox/hosts as it did not pass its verify_file() method
script declined parsing /home/flynn/ansible/playbooks/netbox/hosts as it did not pass its verify_file() method
auto declined parsing /home/flynn/ansible/playbooks/netbox/hosts as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /home/flynn/ansible/playbooks/netbox/hosts inventory source with ini plugin
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'
Loading callback plugin yaml of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/yaml.pyc

PLAYBOOK: netbox_test.yaml *************************************************************************************************************************
Positional arguments: netbox_test.yaml
become_method: sudo
inventory: (u'/home/flynn/ansible/playbooks/netbox/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in netbox_test.yaml
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'

PLAY [Test Netbox modules] *************************************************************************************************************************
META: ran handlers
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'

TASK [netbox_add_device : Create device within Netbox with only required information] **************************************************************
task path: /home/flynn/ansible/playbooks/netbox/roles/netbox_add_device/tasks/main.yml:3
Trying secret ScriptVaultSecret(filename='/home/flynn/ansible/playbooks/netbox/.vault_pass') for vault_id=default
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: flynn
<localhost> EXEC /bin/sh -c 'echo ~flynn && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/flynn/.ansible/tmp/ansible-tmp-1575022930.57-152184130366131 `" && echo ansible-tmp-1575022930.57-152184130366131="` echo /home/flynn/.ansible/tmp/ansible-tmp-1575022930.57-152184130366131 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/net_tools/netbox/netbox_device.py
<localhost> PUT /home/flynn/.ansible/tmp/ansible-local-20280AIzOYI/tmpdNX_Ux TO /home/flynn/.ansible/tmp/ansible-tmp-1575022930.57-152184130366131/AnsiballZ_netbox_device.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/flynn/.ansible/tmp/ansible-tmp-1575022930.57-152184130366131/ /home/flynn/.ansible/tmp/ansible-tmp-1575022930.57-152184130366131/AnsiballZ_netbox_device.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/flynn/.ansible/tmp/ansible-tmp-1575022930.57-152184130366131/AnsiballZ_netbox_device.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/flynn/.ansible/tmp/ansible-tmp-1575022930.57-152184130366131/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_netbox_device_payload_wVETAu/ansible_netbox_device_payload.zip/ansible/modules/net_tools/netbox/netbox_device.py", line 243, in main
  File "/tmp/ansible_netbox_device_payload_wVETAu/ansible_netbox_device_payload.zip/ansible/modules/net_tools/netbox/netbox_device.py", line 267, in ensure_device_present
  File "/tmp/ansible_netbox_device_payload_wVETAu/ansible_netbox_device_payload.zip/ansible/modules/net_tools/netbox/netbox_device.py", line 258, in _find_ids
  File "/tmp/ansible_netbox_device_payload_wVETAu/ansible_netbox_device_payload.zip/ansible/module_utils/net_tools/netbox/netbox_utils.py", line 317, in find_ids
    "Multiple results found while searching for key: %s" % (k)

failed: [localhost] (item={'key': u'device1', 'value': {u'dname': u'test.machine.net', u'dtype': u'Edge Appliance N4040', u'dstate': u'Planned', u'drack': u'TEST-NEW-RACK-01', u'dsite': u'TEST', u'drole': u'NAS', u'dface': u'Front', u'dposition': u'16'}}) => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  ansible_loop_var: item
  invocation:
    module_args:
      data:
        device_role: 25
        device_type: 71
        face: 0
        name: test.machine.net
        position: '16'
        rack: test-new-rack-01
        site: 45
        state: Planned
      netbox_token: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      netbox_url: https://netbox.it.epicgames.com
      state: present
      validate_certs: true
  item:
    key: device1
    value:
      dface: Front
      dname: test.machine.net
      dposition: '16'
      drack: TEST-NEW-RACK-01
      drole: NAS
      dsite: TEST
      dstate: Planned
      dtype: Edge Appliance N4040
  msg: 'Multiple results found while searching for key: rack'

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Looks like it's not using the collections.
**Using module file /usr/lib/python2.7/dist-packages/ansible/modules/net_tools/netbox/netbox_device.py**

**Comment by FragmentedPacket** [comment]
Alright I messed around with this and looks like you don't need to specify anything in regards to collections if all your tasks live in a role.

From my quick look, within your role's tasks, the tasks would look like the following:
```
- name: "Test netbox modules in role"
  fragmentedpacket.netbox_modules.netbox_device:
    netbox_url: "http://netbox-demo.org:32768"
    netbox_token: "0123456789abcdef0123456789abcdef01234567"
    data:
      name: "test100"
  check_mode: yes

OR

- name: "Test netbox modules in role"
  collections:
    - fragmentedpacket.netbox_modules
  netbox_device:
    netbox_url: "http://netbox-demo.org:32768"
    netbox_token: "0123456789abcdef0123456789abcdef01234567"
    data:
      name: "test100"
  check_mode: yes
```

Here is the output when I run a playbook calling my role with the task above:
```
Using module file /root/.ansible/collections/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_device.py
```

Let me know how that goes for you.

**Comment by richardjohnallsopp** [comment]
So running the playbook in the way you suggest uses the collections, but still fails:
````
---
# tasks file for netbox_add_device
    - name: "Create device within Netbox with only required information"
      fragmentedpacket.netbox_modules.netbox_device:
        netbox_url: "https://netbox.it.epicgames.com"
        netbox_token: "{{  netbox_key  }}"
        data:
          name: "{{ item.value.dname }}"
          device_type: "{{ item.value.dtype }}"
          device_role: "{{ item.value.drole }}"
          site: "{{ item.value.dsite }}"
          rack: "{{ item.value.drack }}"
          position: "{{ item.value.dposition }}"
          face: "{{ item.value.dface }}"
          state: "{{ item.value.dstate }}"
          #tags:
            #- nasuni
        state: present
      check_mode: yes  
      loop: "{{ query('dict', devices) }}"
      tags: add_device

````
````
Using module file /home/flynn/.ansible/collections/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_device.py
````
````
flynn@ncl-ansible-01:~/ansible/playbooks/netbox$ ansible-playbook netbox_test.yaml -vvv
ansible-playbook 2.9.1
  config file = /home/flynn/ansible/playbooks/netbox/ansible.cfg
  configured module search path = [u'/home/flynn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
Using /home/flynn/ansible/playbooks/netbox/ansible.cfg as config file
host_list declined parsing /home/flynn/ansible/playbooks/netbox/hosts as it did not pass its verify_file() method
script declined parsing /home/flynn/ansible/playbooks/netbox/hosts as it did not pass its verify_file() method
auto declined parsing /home/flynn/ansible/playbooks/netbox/hosts as it did not pass its verify_file() method
Parsed /home/flynn/ansible/playbooks/netbox/hosts inventory source with ini plugin
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'

PLAYBOOK: netbox_test.yaml *************************************************************************************************************************
1 plays in netbox_test.yaml
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'

PLAY [Test Netbox modules] *************************************************************************************************************************
META: ran handlers
Read vars_file '/home/flynn/ansible/playbooks/netbox/vault/netbox'
Read vars_file '/home/flynn/ansible/playbooks/netbox/group_vars/test_data.yml'

TASK [netbox_add_device : Create device within Netbox with only required information] **************************************************************
task path: /home/flynn/ansible/playbooks/netbox/roles/netbox_add_device/tasks/main.yml:3
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: flynn
<localhost> EXEC /bin/sh -c 'echo ~flynn && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377 `" && echo ansible-tmp-1575046225.15-255471074291377="` echo /home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/flynn/.ansible/collections/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_device.py
<localhost> PUT /home/flynn/.ansible/tmp/ansible-local-22310dq4bsd/tmpfKvQR5 TO /home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/ /home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py", line 102, in <module>
    _ansiballz_main()
  File "/home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fragmentedpacket.netbox_modules.plugins.modules.netbox_device', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_fragmentedpacket.netbox_modules.netbox_device_payload_zEhLM_/ansible_fragmentedpacket.netbox_modules.netbox_device_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_device.py", line 213, in <module>
  File "/tmp/ansible_fragmentedpacket.netbox_modules.netbox_device_payload_zEhLM_/ansible_fragmentedpacket.netbox_modules.netbox_device_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_device.py", line 205, in main
  File "/tmp/ansible_fragmentedpacket.netbox_modules.netbox_device_payload_zEhLM_/ansible_fragmentedpacket.netbox_modules.netbox_device_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/module_utils/netbox_utils.py", line 783, in __init__
TypeError: super() takes at least 1 argument (0 given)

failed: [localhost] (item={'key': u'device1', 'value': {u'dname': u'test.machine.net', u'dtype': u'Edge Appliance N4040', u'dstate': u'Planned', u'drack': u'TEST-NEW-RACK-01', u'dsite': u'TEST', u'drole': u'NAS', u'dface': u'Front', u'dposition': u'16'}}) => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  ansible_loop_var: item
  item:
    key: device1
    value:
      dface: Front
      dname: test.machine.net
      dposition: '16'
      drack: TEST-NEW-RACK-01
      drole: NAS
      dsite: TEST
      dstate: Planned
      dtype: Edge Appliance N4040
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py", line 102, in <module>
        _ansiballz_main()
      File "/home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/flynn/.ansible/tmp/ansible-tmp-1575046225.15-255471074291377/AnsiballZ_netbox_device.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.fragmentedpacket.netbox_modules.plugins.modules.netbox_device', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python2.7/runpy.py", line 188, in run_module
        fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_fragmentedpacket.netbox_modules.netbox_device_payload_zEhLM_/ansible_fragmentedpacket.netbox_modules.netbox_device_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_device.py", line 213, in <module>
      File "/tmp/ansible_fragmentedpacket.netbox_modules.netbox_device_payload_zEhLM_/ansible_fragmentedpacket.netbox_modules.netbox_device_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_device.py", line 205, in main
      File "/tmp/ansible_fragmentedpacket.netbox_modules.netbox_device_payload_zEhLM_/ansible_fragmentedpacket.netbox_modules.netbox_device_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/module_utils/netbox_utils.py", line 783, in __init__
    TypeError: super() takes at least 1 argument (0 given)
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
````
